<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
	<AssemblyOriginatorKeyFile>..\..\..\StrongName\bansi.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bansi.Data" Version="6.0.0" />
    <PackageReference Include="Bansi.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Bansi.EntityFrameworkCore.Common" Version="6.0.0" />
    <PackageReference Include="Bansi.EntityFrameworkCore.FactoryProviders" Version="6.0.0" />
    <PackageReference Include="Bansi.Reflection.AssemblyBindings" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.36" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bansi.CredPC.ModificaCredito.Service.Modelo\Bansi.CredPC.ModificaCredito.Service.Modelo.csproj" />
  </ItemGroup>

</Project>
